Exit if a release proposal is ongoing

diff --git a/.github/workflows/release-dispatch.yml b/.github/workflows/release-dispatch.yml
--- a/.github/workflows/release-dispatch.yml
+++ b/.github/workflows/release-dispatch.yml
@@ -25,9 +25,44 @@ on:
           - libdd-trace-utils
 
 env:
+  MAIN_BRANCH: main
   RELEASE_BRANCH: release
+  PROPOSAL_BRANCH_PREFIX: release-proposal
 
 jobs:
+  check-proposal-ongoing:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+      - name: Check if a release proposal is ongoing
+        run: |
+          # Check if there are any branches with the prefix "${{ env.PROPOSAL_BRANCH_PREFIX }}"
+          git branch -r --list "origin/${{ env.PROPOSAL_BRANCH_PREFIX }}/*"
+          if [ $? -eq 0 ]; then
+            echo "Error: A release proposal is ongoing. Please cancel the ongoing release proposal or wait for it to be merged." >&2
+            exit 1
+          fi
+          echo "No release proposal is ongoing."
+
+  update-release-branch:
+    runs-on: ubuntu-latest
+    needs: check-proposal-ongoing
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+      - name: Merge the main branch into the release branch
+        run: |
+          git fetch origin "${{ env.RELEASE_BRANCH }}" --tags
+          git checkout "${{ env.RELEASE_BRANCH }}"
+          # only fast-forward the merge
+          git merge --ff-only origin/"${{ env.MAIN_BRANCH }}"
+          git push origin "${{ env.RELEASE_BRANCH }}" --tags
+  
   cargo-release:
     permissions:
       id-token: write # Enable OIDC
@@ -84,10 +119,10 @@ jobs:
         run: |
           git checkout "${{ env.RELEASE_BRANCH }}"
           TIMESTAMP=$(date +%Y%m%d-%H%M%S)
-          BRANCH_NAME="release-proposal/${{ inputs.crate }}/$TIMESTAMP"
+          BRANCH_NAME="${{ env.PROPOSAL_BRANCH_PREFIX }}/${{ inputs.crate }}/$TIMESTAMP"
           git checkout -b "$BRANCH_NAME"
           git push origin "$BRANCH_NAME"
-          echo "Branch created: $BRANCH_NAME from $RELEASE_BRANCH branch"
+          echo "Branch created: $BRANCH_NAME from ${{ env.RELEASE_BRANCH }} branch"
           echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
 
       - name: Release version bumps
@@ -276,17 +311,3 @@ jobs:
             --body "$PR_BODY" \
             --base "${{ env.RELEASE_BRANCH }}"
 
-  update-release-branch:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
-        with:
-          fetch-depth: 0
-          fetch-tags: true
-      - name: Merge the main branch into the release branch
-        run: |
-          git fetch origin "${{ env.RELEASE_BRANCH }}" --tags
-          git checkout "${{ env.RELEASE_BRANCH }}"
-          # only fast-forward the merge
-          git merge --ff-only origin/main
-          git push origin "${{ env.RELEASE_BRANCH }}" --tags
